config/routes.rb
Rails.application.routes.draw do

  # sidekiq setup
  require "sidekiq/web"
  authenticate :user, (lambda { |u| u.role == "manager" }) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources  :alerts, only: %i(index show new create update) do
    collection do
      get "select_issue_response"   # /alerts/select_issue_response
      get "select_alert_subgroup"   # /alerts/select_issue_subgroup
      get "select_issue"
    end

  end

  resources :stats, only: %i(index create) do
    collection do
      post "graph_costumer"
      get "customer_list"
    end
  end

  resources :usages, only: %i() do
    collection do
      get "total_usage_and_custommer_with_usage_per_day"
      get "custommer_with_usage_per_week"
    end

  end

  get 'info', to: "pages#info"

  post "users/update_db"

  root to: 'users#index', as: :root
  get 'complate_last_10', to: "users#complate_last_10"

  namespace :api, defaults: { format: :json } do
    namespace :respira do
      namespace :v1 do
        resources :recordings, only: %i[index show update create destroy]
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_token_authenticatable
  
  LANGUAGES = %w[ar en].freeze
  ROLES = %w[manager super_user field_user].freeze

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates :email, email_format: { message: "doesn't look like an email address" }, presence: true
  validates :role, inclusion: { in: ROLES }
  validates :name, uniqueness: true

  has_many :alerts, :class_name => 'Alert', :primary_key => 'created_by'
  has_many :alerts, :class_name => 'Alert', :primary_key => 'user'

  has_many :group_alerts
  
  def role_enum
     ROLES
  end
  
  def manager?
    self.role == "manager"
  end 
  
  def super_user?
    self.role == "super_user"
  end 
  
  def field_user?
    self.role == "field_user"
  end 
  
  def find_alerts # active record does not because we have 2 users in alerts
    Alert.where(user_id: self.id)
  end 
  
  def find_created_by_alerts # active record does not because we have 2 users in alerts
    Alert.where(created_by_id: self.id)
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    policy_scope(User)
    if current_user.field_user?
      redirect_to new_alert_path
    end
  end

  def update_db

    authorize(current_user)
    # pull users database and create new users if they are not in the database
    Customer.update_customer_db
    # create alerts if users have negative accounts
    # Alert.check_customers_with_negative_acount

    flash[:notice] = "database updated successfully!"
    redirect_to root_path
  end

  def complate_last_10
    authorize(current_user)
    if current_user.field_user?
      redirect_to new_alert_path
    end

    alerts = Alert.all_open.order('id desc').offset(10)
    alerts.each do |alert|
      alert.resolved!
    end
    flash[:notice] = "all alerts has been completed except the last 10"
    redirect_to root_path
  end

end

app/views/users/index.html.haml
:sass

  .center
    text-align: center
  .margin
    margin: 30px
  .width-buttom
    width: 200px !important

  .brand-header img
    width: 100px
    margin: 20px

  .brand-header
    background: white
    float: left
    width: 100%
    text-align: center
    margin: 4px 0 0 0

#main-panel

.center{style: "margin-bottom: 100px"}
  %h1
    = "#{current_user.name.capitalize}'s dashboard"
  %p
    -if current_user.role == "manager"
      = "Manager user"
    - else
      = "Super user"
%h4
  = link_to "Admin Panel", rails_admin.dashboard_path, class: 'btn btn-primary btn-lg margin width-buttom', id: "admin-panel-button"
  = "Click here to access the admin dashboard"
%h4
  = link_to "Update Database", users_update_db_path, method: :post, class: 'btn btn-success btn-lg margin width-buttom', id: "update-database-button"
  = "Click here to update database"
%h4
  = link_to "Input Alerts form", new_alert_path, class: 'btn btn-default btn-lg margin width-buttom'
  = "Click here to get access to the input Alerts form"
%h4
  = link_to "Mark as completed", complate_last_10_path, class: 'btn btn-danger btn-lg margin width-buttom'
  = "Click here to show as completed all the alerts exept the last 10"
%p{ style: "margin-top: 150px"}