config/routes.rb
Rails.application.routes.draw do

  # sidekiq setup
  require "sidekiq/web"
  authenticate :user, (lambda { |u| u.role == "manager" }) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources  :alerts, only: %i(index show new create update) do
    collection do
      get "select_issue_response"   # /alerts/select_issue_response
      get "select_alert_subgroup"   # /alerts/select_issue_subgroup
      get "select_issue"
    end

  end

  resources :stats, only: %i(index create) do
    collection do
      post "graph_costumer"
      get "customer_list"
    end
  end

  resources :usages, only: %i() do
    collection do
      get "total_usage_and_custommer_with_usage_per_day"
      get "custommer_with_usage_per_week"
    end

  end

  get 'info', to: "pages#info"

  post "users/update_db"

  root to: 'users#index', as: :root
  get 'complate_last_10', to: "users#complate_last_10"

  namespace :api, defaults: { format: :json } do
    namespace :respira do
      namespace :v1 do
        resources :recordings, only: %i[index show update create destroy]
      end
    end
  end

end

app/views/shared/_flashes.html.haml
:sass

  .alert 
    margin: 0 auto
    width: 40%
    padding: 8px
    margin-bottom: 12px
    text-align: center
    font-size: 0.9em
    font-weight: bold

- if notice
  .alert.alert-info.alert-dismissible{role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
    = notice
- if alert
  .alert.alert-warning.alert-dismissible{role: "alert"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
    = alert

app/views/shared/_navbar.html.haml
:scss

  .navbar-wagon-link.active {
      color: black;
      font-weight: bold;
    }

.navbar-wagon
  / Logo
  = link_to root_path, class: "navbar-wagon-brand" do
    = image_tag "logo/main-logo.png"
    = "Ubuntu Power"
  / Right Navigation
  .navbar-wagon-right.hidden-xs.hidden-sm
    - if user_signed_in?
      / Links when logged in
      = link_to "Statistics", stats_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if current_page?(stats_path)}", id: "stats"
      = link_to "My alerts", alerts_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if current_page?(alerts_path)}", id: "my_alerts"
      = link_to "Info", info_path, class: "navbar-wagon-item navbar-wagon-link #{'active' if current_page?(info_path)}", id: "info"
      / = link_to "Statistics", "#", class: "navbar-wagon-item navbar-wagon-link"
      / Avatar with dropdown menu
      .navbar-wagon-item
        .dropdown
          = image_tag "https://s3-us-west-2.amazonaws.com/colorbuffs/user_data/images/profile/default/default-user.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown"
          %ul.dropdown-menu.dropdown-menu-right.navbar-wagon-dropdown-menu
            %li
              = link_to "#" do
                %i.fa.fa-user
                = t(".profile")
            %li
              = link_to "/" do
                %i.fa.fa-home
                = t(".home")
            %li
              = link_to destroy_user_session_path do
                %i.fa.fa-sign-out
                = t(".sign_out")
    -# - else
    -#   / Login link (when logged out)
    -#   = link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link"
    / Dropdown list appearing on mobile only
  .navbar-wagon-item.hidden-md.hidden-lg
    .dropdown
      %i.fa.fa-bars.dropdown-toggle{"data-toggle" => "dropdown"}
      %ul.dropdown-menu.dropdown-menu-right.navbar-wagon-dropdown-menu
        %li
          = link_to stats_path do
            = t(".statistics")
        %li
          = link_to alerts_path do
            = t(".my_alerts")
        %li
          %a{:href => "/"} 
            = t(".home")
        %li
          = link_to  destroy_user_session_path do
            = t(".sign_out")