config/routes.rb
Rails.application.routes.draw do

  # sidekiq setup
  require "sidekiq/web"
  authenticate :user, (lambda { |u| u.role == "manager" }) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources  :alerts, only: %i(index show new create update) do
    collection do
      get "select_issue_response"   # /alerts/select_issue_response
      get "select_alert_subgroup"   # /alerts/select_issue_subgroup
      get "select_issue"
    end

  end

  resources :stats, only: %i(index create) do
    collection do
      post "graph_costumer"
      get "customer_list"
    end
  end

  resources :usages, only: %i() do
    collection do
      get "total_usage_and_custommer_with_usage_per_day"
      get "custommer_with_usage_per_week"
    end

  end

  get 'info', to: "pages#info"

  post "users/update_db"

  root to: 'users#index', as: :root
  get 'complate_last_10', to: "users#complate_last_10"

  namespace :api, defaults: { format: :json } do
    namespace :respira do
      namespace :v1 do
        resources :recordings, only: %i[index show update create destroy]
      end
    end
  end

end

app/models/alert.rb
class Alert < ApplicationRecord
  
  require 'rest-client'

  STATUS = %w[open resolved].freeze

  belongs_to :customer
  belongs_to :type_alert
  belongs_to :issue

  belongs_to :created_by, class_name: "User"
  belongs_to :user, class_name: "User"

  before_validation :set_created_by, on: :create 
  before_validation :set_assigned_alert_to, on: :create

  validates :customer, presence: true
  validates :user, presence: true
  validates :type_alert, presence: true
  validates :issue, presence: true, if: :resolved?

  # after_save :send_alert_email, if: :production?
  after_commit :send_slack_notification, unless: :test?

  validate :type_alert_for_alert_and_issue_is_the_same, if: :issue? # it ensures that we have chosen the same type_alert in both tables
  validate :customer_cannot_generate_alerts
  
  after_commit :notify_slack_user_created_by, on: :update 

  def set_assigned_alert_to
    self.user = self.type_alert.group_alert.user
  end 

  def set_created_by
    unless test? # TODO: Current.user not working in rspec
      self.created_by = Current.user if Current.user
      self.created_by = User.find_by(name: "Ubuntu") unless Current.user # When a rake tasks is called
    end 
  end 
  
  def self.all_not_hidden
    where(type_alert: TypeAlert.where(hidden_from_graphs: false))
  end 
  
  def self.all_resolved
    where.not(resolved_at: nil)
  end

  def self.all_open
    where(resolved_at: nil)
  end

  def self.my_resolved
    all_resolved.my_alerts.order(created_at: :asc)
  end

  def self.my_open
    all_open.my_alerts.order(created_at: :asc)
  end

  def self.my_alerts
    where(user: Current.user).order(created_at: :asc)
  end 

  def title # to humanize rails admin
    self.type_alert.present? ? self.type_alert.name : "type alert is not present"
  end

  def type_alert_for_alert_and_issue_is_the_same
    unless self.type_alert == self.issue.type_alert
      errors[:type_alert] << "Type Alert has to be the same for Issue and Alert"
    end
  end
  
  def customer_cannot_generate_alerts
    if self.customer.ignore_alerts == true
      errors[:customer] << "Alert cannot be created for this customer"
    end
  end

  def issue?
    true if self.issue.present?
  end

  def resolved?
    true if self.resolved_at
  end

  def send_alert_email
    AlertMailer.perform(self).deliver_later
  end

  def group_alert
    if self.type_alert
      (self.type_alert.group_alert.title).to_s
    end
  end

  def send_slack_notification
    SendNotificationsToSlack.perform_later(self.id)
  end

  def self.notify_an_alert_to_slack(alert_id)
    alert = Alert.find(alert_id)
    user_to_assign_task = if development?
      "@jordi"
    else
      alert.user.slack_username ? alert.user.slack_username : '@laima'
    end 
    user = User.find_by(slack_username: user_to_assign_task)
    Alert.notify_slack_user(user, alert) unless alert.resolved?
    Alert.notify_slack_channel(alert) unless development_or_test?
  end
  
  def self.notify_slack_user(user, alert)
    text = "Hello #{user.name}!\n You have a new alert created (or updated) by #{alert.created_by.try(:name) if alert.created_by.present?} for Customer #{alert.customer.first_name} #{alert.customer.last_name}: id: #{alert.id}, #{alert.type_alert.name} - #{alert.try(:resolved_comments)}\n"
    text << "*You can see your open alerts here* https://ubuntu-power.herokuapp.com/alerts"
    client = Slack::Web::Client.new
    client.auth_test
    client.chat_postMessage(channel: user.slack_username, text: text, as_user: 'ubuntu')
  end 
  
  def notify_slack_user_created_by
    ubuntu_user = User.find_by(slack_username: "@ubuntu")
    if self.resolved? && !test? && self.created_by != ubuntu_user
      user = User.find(self.created_by_id)
      text = "Hello #{self.created_by.try(:name) if self.created_by.present?}!\n Alert resolved by #{self.user.try(:name)} for Customer #{self.customer.first_name} #{self.customer.last_name}: id: #{self.id}, #{self.type_alert.name} - #{self.try(:resolved_comments)}\n"
      client = Slack::Web::Client.new
      client.auth_test
      client.chat_postMessage(channel: user.slack_username, text: text, as_user: 'ubuntu')
    end 
  end
  
  def self.notify_slack_channel(alert)
    text = if alert.resolved?
      "Alert resolved for Customer #{alert.customer.first_name} #{alert.customer.last_name}: id: #{alert.id}, #{alert.type_alert.name}\n"
    else 
      "New alert created (or updated) by #{alert.created_by.try(:name) if alert.created_by.present?} for Customer #{alert.customer.first_name} #{alert.customer.last_name}: id: #{alert.id}, #{alert.type_alert.name} - #{alert.try(:resolved_comments)}\n"
    end 
    client = Slack::Web::Client.new
    client.auth_test
    client.chat_postMessage(channel: "#alerts", text: text, as_user: 'ubuntu')
  end

  def self.notify_open_alerts_to_slack(user)
    alerts = Alert.all_open.where(user: user)
    alerts.sort_by(&:created_at)
    text = "Good Morning #{user.name}! \n You have #{alerts.count} alerts open. \n"
    alerts.each_with_index do |alert, index|
      text << "#{index + 1} - id: #{alert.id}, The customer #{alert.customer.name} has the following issue (created by #{alert.created_by.try(:name) if alert.created_by.present?}) since #{alert.created_at.strftime("%d %m")}: #{alert.type_alert.name} - #{alert.try(:resolved_comments)}\n"
    end 
    text << "*You can resolve your open alerts here* https://ubuntu-power.herokuapp.com/alerts"
    unless test? # TODO: how to stub_request and remove this unless for testing
      client = Slack::Web::Client.new
      client.auth_test
      client.chat_postMessage(channel: user.slack_username, text: text, as_user: 'ubuntu')
    end 
  end

  def resolved!
     self.update_attributes(resolved_at: Time.current)
  end
  
  def unresolved!
     self.update_attributes(resolved_at: nil)
  end

  def closed!
     self.update_attributes(closed_at: Time.current)
  end

  def self.check_customers_with_negative_acount
    Customer.all.each do |customer|
      balance_four_days_ago = Balance.find_by(customer: customer, created_on: Time.zone.today - 4.days)
      balance_today = Balance.find_by(customer: customer, created_on: Time.zone.today)
      if balance_today && balance_four_days_ago
        Alert.create_negative_account(balance_four_days_ago, balance_today, customer)
      end 
    end
  end
  
  def self.create_negative_account(balance_four_days_ago, balance_today, customer)
    if balance_four_days_ago.value_cents <= 0 && balance_today.value_cents <= 0 && !customer.an_alert_open_with?("Negative account") && !customer.ignore_alerts == true
      type_alert = TypeAlert.find_by(name: "Negative account")
      Alert.create!({
          customer: customer,
          type_alert: type_alert,
          issue: Issue.find_by(type_alert: type_alert)
          })
    end
  end 
  
  def self.create_alert_for_customers_with_line_off

    url1 = "https://api.steama.co/bitharvesters/99596/meters/?format=json&page_size=70"
    url2 = "https://api.steama.co/bitharvesters/99596/meters/?format=json&page=2&page_size=70"
    
    [url1, url2].each do |url|
      json_data = if !test?
        body = RestClient.get url, {:Authorization => "Token #{ENV['TOKEN_STEAMA']}"}
        JSON.parse(body)
      else 
        file = Rails.root.join('spec', 'support', 'example_steama_meters.json')
        JSON.parse(File.read(file))
      end 
    
    
      json_data['results'].each do |meter|
        
        id_steama = meter['customer'].to_i
        customer = Customer.find_by(id_steama: id_steama)
        # add condition as an_alert_open_with?("Line is off") does not work if customer is nil
        if customer
          # line_status 4,5,6,7 are line off
          if !meter['connection_is_on'] && !customer.an_alert_open_with?("Line is off") && !customer.an_alert_open_with?("Negative account")
          
          type_alert = TypeAlert.find_by(name: "Line is off")
          Alert.create({
              customer: customer,
              type_alert: type_alert,
              issue: Issue.find_by(type_alert: type_alert)
              })
              
          end
          
        end 
        
      end  
        
    end 
  end
  
  def self.check_meters_exceeding_max_daily_usage

    Meter.all.each do |meter|
      
      json = Usage.generate_usage_json(meter)

      cumulative = 0
      json.map do |usage_hour|
        cumulative += usage_hour["usage"].to_f
      end 
    
      if cumulative > (3 * Usage.max_usage_per_customer)
        type_alert = TypeAlert.find_by(name: "Usage exceeded three times the average")
        @alert = if Alert.create!({
            customer: meter.customer,
            type_alert: type_alert,
            issue: Issue.find_by(type_alert: type_alert),
            resolved_comments: "Total usage was #{cumulative.round(2)} kwh, on #{Date.yesterday}"
            })
        else
          flash[:alert] = @alert.errors.full_messages
          # TODO: send email with there has been a problem
        end
      end
    
    end
  end

end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  before_action :set_alert, only: %i[new show update select_alert_subgroup select_issue]
  
  def index
    alerts = policy_scope(Alert)
    @all_open_alerts = alerts.all_open
    @all_resolved_alerts = alerts.all_resolved
    @my_open_alerts = alerts.my_open
    @my_resolved_alerts = alerts.my_resolved
  end 
  
  def new
    @customers = Customer.all.sort_by(&:first_name).collect {|c| [c.name, c.id]}
    @type_alerts = []
    @issues = []
    @group_alerts = GroupAlert.all.collect {|c| [c.title, c.id]} 
  end
  
  def show 
    issue = @alert.issue.present? ? @alert.issue.name : "Select from previous solutions"
    @issues = []
    @issues << [issue, 1]
    @issues << ["Write your own solution", 2]
    # it does not store the object 'issue' if it existed already in the array
    TypeAlert.find(@alert.type_alert).issues.collect do |c| 
      @issues << [c.name, c.id + 2] unless issue == c.name
    end 
    # remove 'nil' if exist in array
    @resolved = @alert.resolved? ? %w[Yes No] : %w[No Yes]
  end 

  def create
    set_issue_for_create
    @alert = Alert.new(alert_params)
    authorize @alert
    @alert.issue = @issue
    @alert.type_alert = @type_alert || set_type_alert
    
    if @alert.save
      flash[:notice] = "New Alert Created!"
    else
      flash[:alert] = @alert.errors.full_messages
    end
    redirect_to new_alert_path
  end
  
  def update
    set_alert
    set_issue_for_update
    
    if @alert.update_attributes(issue: @issue) && @issue.save
      @alert.resolved! if params[:resolved?] == "Yes"
      @alert.unresolved! if params[:resolved?] == "No"
      flash[:notice] = "Alert #{@alert.id} has been updated!" 
    else
      flash[:alert] = @alert.errors.full_messages || @issue.errors.full_messages
    end  
    redirect_to alerts_path
  end

  def select_issue_response
   # ajax
   @issue = Issue.find(params[:id])
   authorize(@issue)
   render json: [@issue]
  end

  def select_alert_subgroup
   # ajax
   type_alerts = GroupAlert.find(params[:group_alert]).type_alerts.collect {|c| [c.name, c.id]}
   render json: [type_alerts]
  end

  def select_issue
   # ajax
   issues = TypeAlert.find(params[:type_alert]).issues.collect {|c| [c.name, c.id]}
   render json: [issues]
  end

  private

  def set_alert
    @alert = params[:id] ? Alert.find(params[:id]) : Alert.new
    authorize @alert
  end

  def set_issue_for_create
    # if there is some input for 'new issue' description it creates a new alert and issue
    if params[:description_new_alert] != ""
      # first record of GroupAlert and TypeAlert is new
      group_alert = GroupAlert.find_by(id: params[:group_alert])
      @type_alert = TypeAlert.new(name: params[:description_new_alert], group_alert: group_alert)
      show_errors_and_redirect unless @type_alert.save

      @issue = nil # return nil issue
    elsif params[:issue] != "" # if the solution exist
      @issue = Issue.find(params[:issue])
    else # if the solution is not in the list
      @issue = nil
    end
  end
  
  def set_issue_for_update
    @issue = if alert_params[:issue] == "2" # if alert does not exist. It is the selection 'write your own solution')
      Issue.new(type_alert: @alert.type_alert, resolution: params[:resolved_description])
    elsif alert_params[:issue] == "1" # it selects the current issue associated with the alert  
      Issue.find_by(type_alert: @alert.type_alert) 
    else # if the solution is in the list
      Issue.find(alert_params[:issue].to_i - 2) # it substract 2 indices to match id (added previously in #show)
    end
  end 

  def set_type_alert
    TypeAlert.find_by(id: params[:type_alert])
  end

  def alert_params
    params.require(:alert).permit(:customer_id, :issue)
  end

  def show_errors_and_redirect
    flash[:alert] = @alert.errors.full_messages
    redirect_to new_alert_path
  end

end

app/views/alerts/index.html.haml
:sass

  .center 
    text-align: center

  .margin
    margin: 30px

  .nav-tabs > li
    float: none
    display: inline-block
    zoom: 1

  .nav-tabs 
    text-align: center

.center{style: "margin-bottom: 50px"}
  %h1

#show_my_alerts
#exTab2.container
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", :href => "#1"} My Open Alert
    %li
      %a{"data-toggle" => "tab", :href => "#2", id: "resolved-alerts"} My Resolved Alerts
    %li
      %a{"data-toggle" => "tab", :href => "#3"} All Open Alerts
    %li
      %a{"data-toggle" => "tab", :href => "#4"} All Resolved Alerts
  .tab-content
    #1.tab-pane.active
      %p.margin.center
        - unless current_user.role == "field_user"
          = "Click here to see more info about your alerts"
          %br/
          = link_to "Alerts in Admin Panel", "/admin/alert?model_name=alert&scope=my_open", class: 'btn btn-primary btn-lg margin width-buttom'
      %table.table.table-striped
        - if @my_open_alerts.any? 
          %thead
            %tr
              %th.center Id
              %th.center Customer
              %th.center Type alert
              %th.center Created by
              %th.center Created at
              %th.center Notes
              %th.center Solution
              %th.center Resolve (click)
            %tbody
              - @my_open_alerts.each do |alert|
                #my_open_alert
                %tr
                  %td
                    = alert.id
                  %td.col-md-2
                    = alert.customer.name
                  %td.col-md-3
                    = alert.type_alert.name
                  %td.col-md-1
                    = alert.created_by.try(:name)
                  %td.col-md-1
                    = alert.created_at
                  %td.col-md-2
                    = alert.resolved_comments 
                  %td.col-md-2
                    = alert.issue.try(:resolution)
                  %td.col-md-2.center
                    = link_to alert_path(alert) do
                      .fa.fa-check

                    
        - else 
          %h4.center
            = "Well done #{current_user.name}! You do not have open alerts"    
    #2.tab-pane
      %p.margin
        %p.center
          = "You resolved #{@my_resolved_alerts.count} alerts so far"
        %br/
      %table.table.table-striped
        %thead
          %tr
            %th.center Id
            %th.center Customer
            %th.center Type alert
            %th.center Created by
            %th.center Created at
            %th.center Notes
            %th.center Solution
            %th.center Unresolve (click)
        %tbody
          - if @my_resolved_alerts.any?
            - @my_resolved_alerts.each do |alert|
              %tr
                %td
                  = alert.id
                %td.col-md-2
                  = alert.customer.name
                %td.col-md-3
                  = alert.type_alert.name
                %td.col-md-1
                  = alert.created_by.try(:name)
                %td.col-md-1
                  = alert.created_at
                %td.col-md-2
                  = alert.resolved_comments 
                %td.col-md-2
                  = alert.issue.try(:resolution) 
                %td.col-md-2.center
                  = link_to alert_path(alert) do
                    .fa.fa-times
    #3.tab-pane
      %table.table.table-striped
        %thead
          %tr
            %th.center Id
            %th.center Customer
            %th.center Type alert
            %th.center Assigned
            %th.center Created by
            %th.center Created at
            %th.center Notes
            %th.center Solution
            %th.center Resolve (click)
        %tbody
          - if @all_open_alerts.any?
            - @all_open_alerts.each do |alert|
              %tr
                %td
                  = alert.id
                %td.col-md-2
                  = alert.customer.name
                %td.col-md-3
                  = alert.type_alert.name
                %td.col-md-1
                  = alert.user.try(:name)
                %td.col-md-1
                  = alert.created_by.try(:name)
                %td.col-md-1
                  = alert.created_at
                %td.col-md-2
                  = alert.resolved_comments 
                %td.col-md-2
                  = alert.issue.try(:resolution) 
                %td.col-md-2.center
                  = link_to alert_path(alert) do
                    .fa.fa-check
    #4.tab-pane
      %table.table.table-striped
        %thead
          %tr
            %th.center Id
            %th.center Customer
            %th.center Type alert
            %th.center Assigned
            %th.center Created by
            %th.center Created at
            %th.center Notes
            %th.center Solution
            %th.center Unresolve (click)
        %tbody
          - if @all_resolved_alerts.any? 
            - @all_resolved_alerts.each do |alert|
              %tr
                %td
                  = alert.id
                %td.col-md-2
                  = alert.customer.name
                %td.col-md-3
                  = alert.type_alert.name
                %td.col-md-1
                  = alert.user.try(:name)
                %td.col-md-1
                  = alert.created_by.try(:name)
                %td.col-md-1
                  = alert.created_at
                %td.col-md-2
                  = alert.resolved_comments 
                %td.col-md-2
                  = alert.issue.try(:resolution)
                %td.col-md-2.center
                  = link_to alert_path(alert) do
                    .fa.fa-times
%hr/

app/views/alerts/new.html.haml
:sass

  .center 
    text-align: center
    
  .brand-header img 
    width: 100px
    margin: 20px
  
  .brand-header
    background: white
    float: left
    width: 100%
    text-align: center
    margin: 4px 0 0 0

#alerts-new
.row
  .col-md-offset-3.col-md-6
    #login.brand-header
      = image_tag 'logo/main-logo.png', class: 'main-logo'
%h1.center{style: "margin-bottom: 100px"}
  Ubuntu Power
.row
  .panel-default.col-md-offset-2.col-md-8.center
    %h4
      = "Create an Alert"
    %p
      Please fill in this form to create a new alert
    .row
      .col-md-offset-2.col-md-8
        = simple_form_for Alert.new, url: alerts_path, method: :post do |f|
          = f.error_notification
          = render 'shared/flashes'
          = f.input :customer_id, label: false, collection: @customers, prompt: "Select customer" 
          = f.input :group_alert, as: :fake_select, label: false, collection: @group_alerts, prompt: "Select alert group"
          = f.input :type_alert, as: :fake_select, label: false, collection: @type_alerts, prompt: "Select alert"
          #new-resolved-response
            = f.input :issue, as: :fake_select, label: false, collection: @issues, prompt: "Select from previous solution"
            %p
              #resolved-description{ style: "margin: 30px" }
            -#= f.input :resolved_description, as: :fake, label: false, placeholder: "If previous response does not exists, please explain", autofocus: true
          #new-type-alert
            = f.input :description_new_alert, as: :fake, label: false, placeholder: 'Add new alert description', autofocus: true
          = f.button :submit, "Create Alert", class: "button btn btn-lg btn-primary", id: "submit-button"
      
.row
  .col-md-offset-3.col-md-8.center{ style: "margin:30px"}
    = "To sign out click here:"
    = link_to t('.sign_out', default: 'Sign out'), destroy_user_session_path
    
- content_for :bottom_js do
  :javascript
    // https://stackoverflow.com/questions/38202484/simple-form-select-collection-populated-by-ajax-call
    
    // update dropdown for subgroup
    $('#group_alert').change(function(){
      $.ajax({
        url: 'select_alert_subgroup',
        dataType: 'json',
        type: 'GET',
        data: {
          group_alert: this.value
        },
        success: function(data) {
          
          // Populate second dropdown here
          var output = '';
          $('#type_alert').empty().append(function() {
            output += "<option value>"  + "Select Alert" + "</option>"
            output += "<option value='new'>"  + "Create new alert" + "</option>"
            data.forEach(function(item) {
              item.forEach(function(subitem){
              // subitem is the vale HTML parameter which is added + 1 as the first one is the description
                output += "<option value =" + subitem[1] + ">"  + subitem[0] + "</option>"
              });
            });
            return output;
          });
        }
      });
    });

    // update drowndown of posible responses
    $('#type_alert').change(function(){
      $.ajax({
        url: 'select_issue',
        dataType: 'json',
        type: 'GET',
        data: {
          type_alert: this.value
        },
        success: function(data) {
          // Populate second dropdown here
          var output = '';
          $('#issue').empty().append(function() {
            output += "<option value>"  + "Select possible solution" + "</option>"
            output += "<option value>"  + "I don't find the a solution in the list" + "</option>"
            data.forEach(function(item) {
              item.forEach(function(subitem){
                // subitem is the vale HTML parameter which is added + 1 as the first one is the description
                output += "<option value =" + subitem[1] + ">"  + subitem[0] + "</option>"
              });
            });
            return output;
          });
        }
      });
    });

    // copy possible response in empty field
    $('#issue').change(function(){
      $.ajax({
        url: 'select_issue_response',    
        dataType: 'json',
        type: 'GET',
        data: {
          id: this.value
        },
        success: function(data) {
          // $('#resolved-description').val();
          $('#resolved-description').empty().append(data[0].resolution)
        }  
      });
    });

app/views/alerts/show.html.haml
:sass

  .center 
    text-align: center
    
  .brand-header img 
    width: 100px
    margin: 20px
  
  .brand-header
    background: white
    float: left
    width: 100%
    text-align: center
    margin: 4px 0 0 0
    
  .margin-text-alert 
    margin: 30px

#alerts-show
.row
  .panel-default.col-md-offset-3.col-md-6.center
    %h3.center{style: "margin-top: 100px"}
      = "Resolve/UnResolve Alert"
      = @alert.id
    %p{style: "margin-bottom: 50px"}
      Please create a solution and marked as resolved the alert, by updating this form
    
    = simple_form_for Alert.new, url: alert_path, method: :patch do |f|
      = f.error_notification
      = render 'shared/flashes'
      .margin-text-alert 
        %strong
          = "Customer:"
        = "#{@alert.customer.name}, mobile #{@alert.customer.telephone}"
      .margin-text-alert 
        %strong
          = "Group Alert:"
        = "#{@alert.type_alert.group_alert.title}"
      .margin-text-alert 
        %strong
          = "Type Alert:"
        = "#{@alert.type_alert.name}"
      .margin-text-alert
        = f.input :issue, label: "Solution", collection: @issues, :selected => 1
        = f.input :resolved_description, as: :fake, label: false, placeholder: "If previous solution does not exists, please explain how this was solved", autofocus: true
        = f.input :resolved?, as: :fake_select, collection: @resolved, :selected => 1
      = f.button :submit, "Update Alert", class: "button btn btn-lg btn-primary", id: "submit-button"
.row
  .col-md-offset-3.col-md-8.center{ style: "margin:30px"}
    = "To sign out click here:"
    = link_to t('.sign_out', default: 'Sign out'), destroy_user_session_path