config/routes.rb
Rails.application.routes.draw do

  # sidekiq setup
  require "sidekiq/web"
  authenticate :user, (lambda { |u| u.role == "manager" }) do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  resources  :alerts, only: %i(index show new create update) do
    collection do
      get "select_issue_response"   # /alerts/select_issue_response
      get "select_alert_subgroup"   # /alerts/select_issue_subgroup
      get "select_issue"
    end

  end

  resources :stats, only: %i(index create) do
    collection do
      post "graph_costumer"
      get "customer_list"
    end
  end

  resources :usages, only: %i() do
    collection do
      get "total_usage_and_custommer_with_usage_per_day"
      get "custommer_with_usage_per_week"
    end

  end

  get 'info', to: "pages#info"

  post "users/update_db"

  root to: 'users#index', as: :root
  get 'complate_last_10', to: "users#complate_last_10"

  namespace :api, defaults: { format: :json } do
    namespace :respira do
      namespace :v1 do
        resources :recordings, only: %i[index show update create destroy]
      end
    end
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  
  before_action :format_dates, only: %i[index create]
  before_action :load_costumers, only: %i[index create]
  before_action :skip_authorization, only: %i[create graph_costumer customer_list]
  before_action :load_dates, only: %i[graph_costumer customer_list]
  
  def index
    policy_scope(User)
  end
  
  def create 
    @show_usage = params[:include_usage] == "yes" ? true : false
    respond_to do |format|
      format.js
    end
  end 
  
  def graph_costumer
    @customer = Customer.find(params["customer_id"].to_i)
  end 
  
  def customer_list
  end 
  
  private
  
  def load_costumers
    @customers = Customer.all.sort_by(&:first_name).collect {|c| [c.name, c.id]}
  end
  
  def format_dates
    @start_date = params[:start_date].blank? ? 2.weeks.ago.midnight : params[:start_date].to_datetime.midnight
    @end_date = params[:end_date].blank? ? Time.current.at_end_of_day : params[:end_date].to_datetime.at_end_of_day
    
    # sessions used into the usage controller
    session[:start_date] = @start_date
    session[:end_date] = @end_date 
  end 
  
end

app/helpers/stats_helper.rb
module StatsHelper

  def alerts_by_type_alert
    data = Alert.all.joins(:type_alert).group("type_alerts.name").count # https://github.com/ankane/chartkick/issues/19
    bar_chart data, xtitle: "num. of alerts", ytitle: ""
  end
  
  def alerts_by_type_alert_dunut
    # data = Alert.all.group(:type_alert).count
    data = Alert.all.joins(:type_alert).group("type_alerts.name").count
    pie_chart data, donut: true, legend: "bottom"
  end
  
  def alerts_by_user
    data = Alert.all.joins(:user).group("users.name").count
    column_chart data, xtitle: "", ytitle: ""
  end
  
end

app/views/stats/_alerts_graphs.html.haml
#alerts_graphs
  %p.title-graph 
  = total_alerts_in_time
  %p.title-graph 
  = alerts_by_time
  %p.title-graph 
  -# = alerts_by_group_alert_donut
  %p.title-graph
  = alerts_by_type_alert
  %p.title-graph 
  -# = alerts_by_group_alert
  %p.title-graph
  = top_10_solutions

app/views/stats/_customers_graphs.html.haml
:sass

  .center 
    text-align: center

  .margin
    margin: 30px

  .nav-tabs > li
    float: none
    display: inline-block
    zoom: 1

  .nav-tabs 
    text-align: center


#customers_graphs
  %p.title-graph 
  = top_10_customers_with_more_usage("asc")
  %p.title-graph
  = top_10_customers_with_more_alerts("asc")
  %p.title-graph
  %br/  
  .row
    .panel-default.col-md-offset-2.col-md-8.center
      %h4
        = "Select Costumer"
      .row
        .col-md-offset-2.col-md-8
          = simple_form_for Customer.new, url: graph_costumer_stats_path, method: :post do |f|
            = f.error_notification
            = render 'shared/flashes'
            = f.input :customer_id, as: :fake_select, label: false, collection: @customers, prompt: "Select customer" 
            = f.button :submit, "Generate Individual Report", class: "button btn btn-lg btn-primary"
      

app/views/stats/_topups_graphs.html.haml
:sass

  #button_customers
    text-align: center
    margin-top: 30px
    margin-bottom: 30px
    
#topups_graphs
  #button_customers
    = link_to "Display customers sorted by topups", customer_list_stats_path , class: "button btn btn-lg btn-primary", id: "display-customers"
  = top_10_customers_with_topups("asc")
  = top_10_customers_with_topups_in_time
  = top_10_customers_with_topups_sum("asc")
  = top_10_customers_with_topups_in_time_sum

app/views/stats/_usage_graphs.html.haml
#usage_graphs
  %p.title-graph 
    = day_usage_cumulative
  - if @show_usage
    %p.title-graph
      = "Click here to see total usage and usages per day reports (it may take some time to load)"
      %br/
      .title-graph{style: "margin: 50px"} 
        = link_to "Generate reports", total_usage_and_custommer_with_usage_per_day_usages_path, class: 'btn btn-primary btn-lg margin width-buttom', id: "usages-1"
    %p.title-graph
      = "Click here to see usage per weeks reports (it may take some time to load)"
      %br/
      .title-graph{style: "margin: 50px"} 
        = link_to "Generate weekly reports", custommer_with_usage_per_week_usages_path, class: 'btn btn-primary btn-lg margin width-buttom', id: "usages-2"
      
    

app/views/stats/_users_graphs.html.haml
#users_graphs
  %p.title-graph 
  = assigned_alerts
  %p.title-graph 
  = alerts_by_user
  %p.title-graph 
  = alerts_by_user_in_time("alerts.created_at") 
  %p.title-graph 
  = alerts_by_user_in_time("alerts.resolved_at") 
  %p.title-graph 
  = alerts_created_by_user

app/views/stats/create.js.erb
$('#alerts_graphs').replaceWith('<%= j render 'alerts_graphs' %>');
$('#customers_graphs').replaceWith('<%= j render 'customers_graphs' %>');
$('#users_graphs').replaceWith('<%= j render 'users_graphs' %>');
$('#usage_graphs').replaceWith('<%= j render 'usage_graphs' %>');
$('#topups_graphs').replaceWith('<%= j render 'topups_graphs' %>');

app/views/stats/customer_list.html.haml
:sass

  .center 
    text-align: center
  .tariff_1
    color: green
  .tariff_2
    color: blue
  .tariff_3
    color: brown
  .tariff_text
    font-size: 30px
    text-align: center
    margin-top: 20px
    margin-bottom: 20px
  .wrong_tariff
    background-color: #f9b1ab !important
  .title_list
    font-weight: bold 
    font-size: 20px 
    text-align: center
    margin-top: 30px

- num_of_customers = 119 # Customers
- sort_customers_with_topups_in_time_sum
- n = 0
- tariff_num = 0
- a = 0
- b = 14
- c = num_of_customers - 47
- data_tariff_1 = @data_sorted[a..b] # top 15 customers
- data_tariff_2 = @data_sorted[(b+1)..c]
- data_tariff_3 = @data_sorted[(c+1)..num_of_customers] # bottom 44 customers

= link_to 'Back', :back, class: 'btn btn-default btn-lg margin', style: "margin-top: 30px"

.title_list
  = "List of customers sorted by sum of topups -  #{@start_date.strftime('%d %b %Y')} to #{@end_date.strftime('%d %b %Y')}"
- [data_tariff_1, data_tariff_2, data_tariff_3].each do |tariff|
  - if tariff.present?
    - tariff_num += 1
    %div{style: "margin-top: 50px"}
      %table.table.table-striped.center
        .tariff_text{class: "tariff_#{tariff_num}"}
          = "Tariff"
          = tariff_num
          = "("
          = tariff.count 
          = "Customers):"
          = Customer.tariff(tariff_num).to_i 
          = "KES"
        %thead
          %tr{class: "tariff_#{tariff_num}"}
            %th.center Global Position
            %th.center Total Spend period (KES)
            %th.center Id steama
            %th.center Id 
            %th.center First Name
            %th.center Last Name
            %th.center Energy Price
            %th.center Account Balance
        %tbody
          - tariff.each do |customer|
            - customer_db = Customer.find(customer[:id])
            - n += 1
            %tr{class: "tariff_#{tariff_num} #{'wrong_tariff' unless customer_db.energy_price == Customer.tariff(tariff_num)}"}
              %td.col-md-2
                = n
              %td.col-md-2
                = customer[:cumulative]
              %td.col-md-2
                = customer_db.id_steama
              %td.col-md-2
                = customer_db.id
              %td.col-md-2
                = customer_db.first_name
              %td.col-md-2
                = customer_db.last_name
              %td.col-md-2
                = customer_db.energy_price
              %td.col-md-2
                = customer_db.account_balance                    

app/views/stats/graph_costumer.html.haml
:sass
  .col-centered
    float: none
    margin: 0 auto
    
  .title-graph 
    font-weight: bold
    text-align: center
    margin: 40px
  
  .nav-tabs > li
    float: none
    display: inline-block
    zoom: 1

  .nav-tabs 
    text-align: center
    
  // overides highcharts font size
  .highcharts-title 
    font-weight: bold !important
    font-size: 14px !important

= link_to 'Back', :back, class: 'btn btn-default btn-lg margin', style: "margin-top: 30px"

%p.title-graph 
  = customer_indivicual_graph_topups_in_time
  = customer_indivicual_graph_in_time_sum
  
  

app/views/stats/index.html.haml
:sass
  .col-centered
    float: none
    margin: 0 auto
    
  .title-graph 
    font-weight: bold
    text-align: center
    margin: 40px
  
  .nav-tabs > li
    float: none
    display: inline-block
    zoom: 1

  .nav-tabs 
    text-align: center
    
  // overides highcharts font size
  .highcharts-title 
    font-weight: bold !important
    font-size: 14px !important

#show_my_alerts

.row
  .col-sm-12
    #event_period.row{style: "margin: 50px"}
      = form_tag stats_path, remote: true do
        .col-sm-1
          %label{:for => "start_date"} Start date
        .col-sm-3
          .input-group
            %input#start_date.actual_range.form-control.datepicker{:name => "start_date", :type => "text"}/
            .input-group-addon
              %span.glyphicon.glyphicon-th
        .col-sm-1
          %label{:for => "end_date"} End date
        .col-sm-3
          .input-group
            %input#end_date.actual_range.form-control.datepicker{:name => "end_date", :type => "text"}/
            .input-group-addon
              %span.glyphicon.glyphicon-th
        .col-sm-2{ style: "text-align: center" }
          %input{:name => "include_usage", :type => "checkbox", :value => "yes", id: "include-usage" }/
          %br
          = "Tick to include"
          %br
          %p 
            = "Usages reports"
        -# .col-sm-2{ style: "text-align: center" }
        -#   %input{:name => "include_topups", :type => "checkbox", :value => "yes", id: "include_topups" }/
        -#   %br
        -#   = "Tick to include "
        -#   %br
        -#   %p 
        -#     = "Top-ups (slow)"
        .col-sm-2
          = submit_tag 'Update stats', class: 'btn btn-primary', id: "update-stats"

#exTab2.container
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", :href => "#1"} Alerts 
    %li
      %a{"data-toggle" => "tab", :href => "#2", id: "user-tab"} Users
    %li
      %a{"data-toggle" => "tab", :href => "#3"} Customers
    %li
      %a{"data-toggle" => "tab", :href => "#4", id: "usage-tab"} Usage
    %li
      %a{"data-toggle" => "tab", :href => "#5", id: "top-up"} Top-ups 
  .tab-content
    #1.tab-pane.active
      = render partial: 'alerts_graphs'
    #2.tab-pane
      = render partial: 'users_graphs'
    #3.tab-pane
      = render partial: 'customers_graphs'
    #4.tab-pane
      = render partial: 'usage_graphs'
    #5.tab-pane
      = render partial: 'topups_graphs'

- content_for :bottom_js do
  -# Boostrap is not compatible with nav-tabs and chart.js https://github.com/ankane/chartkick/issues/28 && https://github.com/chartjs/Chart.js/issues/512
  :javascript
  
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
    
      var chart = Chartkick.charts["total-alerts-by_user"]
      chart.redraw();
      var chart = Chartkick.charts["alerts-by-user-in-time"]
      chart.redraw();
      var chart = Chartkick.charts["resolved-alerts-by-user-in-time"]
      chart.redraw();
      var chart = Chartkick.charts["chart-5"]
      chart.redraw();
      var chart = Chartkick.charts["top-10-customers-with-more-usage"]
      chart.redraw();
      var chart = Chartkick.charts["top-10-customers-with-more-alerts"]
      chart.redraw();
      var chart = Chartkick.charts["top-10-customers-with-more-topups"]
      chart.redraw();
      var chart = Chartkick.charts["top-10-customers-with-more-topups-sum"]
      chart.redraw();
    });
    
    $(document).ready(function() {
      $('#event_period').datepicker({
        inputs: $('.actual_range'),
        startDate: '-3y',
        endDate: '0d',
        todayBtn: 'linked',
        todayHighlight: 'true',
        format: 'yyyy-mm-dd'
      });
    });
      

app/views/stats/montly_graphs.html.haml
:sass
  .title-graph 
    font-weight: bold
    text-align: center
    margin: 40px


%p.title-graph 
  = "Hourly usage last month"
= monthly_usage(DateTime.current-1.month)
%p.title-graph 
  = "Hourly usage this month"
= monthly_usage(DateTime.current)